name: Push mirror

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      KEY:
        required: true

env:
  MIRROR_URL: "git@github.com:EpitechPromo2027/B-CNA-500-PAR-5-1-neuralnetwork-rahul.chander.git"

jobs:
  push_to_mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror the repo
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.KEY }}
